name: Sagemind
description: "An Expert Education System For High Schoolers."
publish_to: 'none'
version: 0.9.5

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^6.1.0
  shared_preferences: ^2.2.2
  supabase: ^2.10.0
  file_picker: ^10.3.7
  video_player: ^2.10.1
  supabase_flutter: ^2.10.3
  permission_handler: ^11.3.0
  device_info_plus: ^12.3.0
  url_launcher: ^6.3.2
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  cloud_firestore: ^6.1.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo sagemind.png"
